<?php

namespace AppBundle\Repository;

/**
 * ContributionHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
