<?php

namespace AppBundle\Repository;

/**
 * ContributorDoubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributorDoubleRepository extends \Doctrine\ORM\EntityRepository
{
}
