<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensioLabsUserRepository extends \Doctrine\ORM\EntityRepository
{
}
