imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services_repositories.yml }
    - { resource: services.yml }
    - { resource: services_aggregators.yml }
    - { resource: trends_charts.yml }

parameters:
    locale: en
    maintenance_commit_patterns:
        - '^minor #'
        - '^bug #'
        - '^feature #'
        - '^merged branch'
        - '^Merge branch'
        - '^merged '
        - '^Merge remote-tracking branch'
        - '^Merge pull request #'
        - '^updated VERSION'
        - '^update CONTRIBUTORS'
        - '^updated CHANGELOG'
        - '^bumped Symfony version to'
        - '^updated version to'
        - '^fix merge'
        - '^fixed merge'
        - '^fixed bad merge'
        - '^Revert "'
        - '^Revert #'

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
