services:

    #################################
    # Data aggregators
    #################################
    aggregator_registry:
        class: Aa\ATrends\Aggregator\AggregatorRegistry

    aggregator_runner:
        class: Aa\ATrends\Aggregator\Runner\Runner
        arguments:
            - '@repository.project'
            - '@event_dispatcher'

    aggregator_report_dumper:
        class: AppBundle\Aggregator\Report\ReportDumper

    aggregator.sensiolabs_profile:
        class: AppBundle\Aggregator\SensiolabsProfileAggregator
        lazy: true
        arguments:
            - '@api.contributor_page'
            - '@api.sensiolabs_connect'
            - '@repository.sensiolabs_user'
            - '@repository.contributor'
            - '%sensiolabs_profile_uri%'
            - '%github_profile_uri%'
        tags:
            - { name: aggregator, alias: 'sensiolabs-profiles'}

    aggregator.github_commit:
        class: Aa\ATrends\Aggregator\CommitAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.contributor'
            - '@repository.contribution'
            - '%maintenance_commit_patterns%'
        calls:
            - ['setProgressNotifier', ['@trends.progress.notifier']]
        tags:
            - { name: aggregator, alias: 'commits'}

    aggregator.contributor_country:
        class: Aa\ATrends\Aggregator\ContributorCountryAggregator
        lazy: true
        arguments:
            - '@api.geocoder'
            - '@repository.contributor'
        calls:
            - ['setProgressNotifier', ['@trends.progress.notifier']]
        tags:
            - { name: aggregator, alias: 'contributor-countries'}

    aggregator.github_issue:
        class: Aa\ATrends\Aggregator\IssueAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.issue'
            - '@repository.pull_request'
        calls:
            - ['setProgressNotifier', ['@trends.progress.notifier']]
        tags:
            - { name: aggregator, alias: 'issues'}

    aggregator.github_pull_request:
        class: Aa\ATrends\Aggregator\PullRequestAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.pull_request'
            - '@helper.pull_request_body_processor'
        calls:
            - ['setProgressNotifier', ['@trends.progress.notifier']]
        tags:
            - { name: aggregator, alias: 'pull-requests'}

    aggregator.github_pull_request_review:
        class: Aa\ATrends\Aggregator\PullRequestReviewAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.pull_request'
        calls:
            - ['setProgressNotifier', ['@trends.progress.notifier']]
        tags:
            - { name: aggregator, alias: 'pull-request-reviews'}
