services:
    http_client:
        class: AppBundle\Client\HttpClient
    github_client:
        class: Github\Client
    github_api_client:
        class: AppBundle\Client\GithubApiClient
        arguments:
            - '@http_client'
            - '%env(GITHUB_CLIENT_ID)%'
            - '%env(GITHUB_CLIENT_SECRET)%'
    geolocation_api_client:
        class: AppBundle\Client\GeolocationApiClient
        arguments:
            - '@http_client'
            - '%env(GEOCODING_API_KEY)%'

    data_provider:
        class: AppBundle\Repository\DataProvider
        autowire: true

    series_provider:
        class: AppBundle\Provider\SeriesProvider
        autowire: true

    #################################
    # Helpers
    #################################
    helper.contributor_extractor:
        class: AppBundle\Aggregator\Helper\ContributorExtractor
        lazy: true

    helper.sensiolabs_data_extractor:
        class: AppBundle\Aggregator\Helper\SensiolabsDataExtractor
        lazy: true

    #################################
    # Data aggregators
    #################################
    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPage
        arguments:
            - '@http_client'
            - '@helper.contributor_extractor'
            - '@repository.contributor'

    aggregator.github_user_data:
        class: AppBundle\Aggregator\GithubUserData
        lazy: true
        arguments:
            - '@github_api_client'
            - '@geolocation_api_client'
            - '@repository.contributor'

    aggregator.github_commit_history:
        class: AppBundle\Aggregator\GithubCommitHistory
        lazy: true
        arguments:
            - '@github_api_client'
            - '@geolocation_api_client'
            - '@repository.project'
            - '@repository.contribution'
            - '@repository.contributor'

    aggregator.sensiolabs_connect:
        class: AppBundle\Aggregator\SensiolabsConnect
        lazy: true
        arguments:
            - '@http_client'
            - '@helper.sensiolabs_data_extractor'
            - '@repository.contributor'

    #################################
    # Data providers
    #################################
    formatter.highcharts:
        class: AppBundle\Formatter\Highcharts
        lazy: true

    formatter.highmaps:
        class: AppBundle\Formatter\Highmaps
        lazy: true

    provider.contributors_intersection:
        class: AppBundle\Provider\ContributorsIntersection
        lazy: true
        arguments:
            - '@repository.contribution'
            - '@repository.project'

    provider.commit_count_distribution:
        class: AppBundle\Provider\CommitCountDistribution
        lazy: true
        arguments:
            - '@repository.contribution'
            - '@repository.project'

    provider.contributors_per_country:
        class: AppBundle\Provider\ContributorsPerCountry
        lazy: true
        arguments:
            - '@repository.contributor'

    provider.contributions_per_date:
        class: AppBundle\Provider\ContributionsPerDate
        lazy: true
        arguments:
            - '@repository.contribution'
            - '@repository.project'
