parameters:
    github_profile_uri: 'gh/'

services:

    github_api.fake_guzzle_client:
        class: features\Aa\ATrends\Fake\FakeHttpClient

    api.http_client:
        class: Http\Adapter\Guzzle6\Client
        arguments:
            - '@github_api.fake_guzzle_client'

    doctrine.orm.purger:
        class: Doctrine\Common\DataFixtures\Purger\ORMPurger
        arguments:
            - '@doctrine.orm.entity_manager'

    behat_doctrine_helper:
        class: features\Aa\ATrends\Helper\DoctrineHelper
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.orm.purger'

    # Fake clients
    api.github:
        class: features\Aa\ATrends\Fake\GithubApi

    api.geocoder:
        class: features\Aa\ATrends\Fake\GeocoderApi

    api.contributor_page:
        class: features\Fake\ContributorPageApi

    api.sensiolabs_connect:
        class: features\Fake\SensiolabsApi

    api.list:
        class: features\Aa\ATrends\Helper\ApiCollection
        calls:
            - [ add, ['Github', '@api.github']]
            - [ add, ['Geocoder', '@api.geocoder']]
            - [ add, ['ContributorPage', '@api.contributor_page']]
            - [ add, ['Sensiolabs', '@api.sensiolabs_connect']]
