services:
    http_client:
        class: GuzzleHttp\Client
    #################################
    # Data aggregators
    #################################
    aggregator.contributor_count:
        class: AppBundle\Aggregator\ContributorCount
        arguments:
            - '@http_client'
            - '@repository.project_version'

    aggregator.contributor_count2:
        class: AppBundle\Aggregator\ContributorCount2
        arguments:
            - '@repository.project_version'
            - '@repository.contribution_history'

    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPage
        arguments:
            - '@http_client'
            - '@repository.contributor'
    aggregator.git_log:
        class: AppBundle\Aggregator\GitLog
        arguments:
            - '@repository.contributor'
            - '@repository.contribution'
            - '@repository.contribution_history'
            - '%kernel.root_dir%'

    #################################
    # Data providers
    #################################
    provider.contributors_intersection:
        class: AppBundle\Provider\ContributorsIntersection
        arguments:
            - '@repository.contribution'
            - '@repository.project'
    provider.commit_count_distribution:
        class: AppBundle\Provider\CommitCountDistribution
        arguments:
            - '@repository.contribution'
            - '@repository.project'
    provider.contributors_per_version:
        class: AppBundle\Provider\ContributorsPerVersion
        arguments:
            - '@repository.project_version'
    provider.contributors_per_date:
        class: AppBundle\Provider\ContributorsPerDate
        arguments:
            - '@repository.contribution'
