services:

    github_api.plugin.wait_and_retry:
        class: AppBundle\Client\Github\WaitAndRetryPlugin
        arguments:
            - '@event_dispatcher'

    github_api.plugin.authentication:
        class: Github\HttpClient\Plugin\Authentication
        arguments:
            - '%env(GITHUB_CLIENT_ID)%'
            - '%env(GITHUB_CLIENT_SECRET)%'
            - 'url_client_id'

    github_api.http_client:
        class: Http\Adapter\Guzzle6\Client

    github_api.http_client_builder:
        class: Github\HttpClient\Builder
        arguments:
            - '@github_api.http_client'

    github_api.client_configurator:
        class: AppBundle\Client\Github\ClientConfigurator
        arguments:
            - '@github_api.http_client_builder'
            - ['@github_api.plugin.wait_and_retry', '@github_api.plugin.authentication']

    github_api.client:
        class: Github\Client
        arguments:
            - '@github_api.http_client_builder'
        configurator: ['@github_api.client_configurator', 'configure']

    github_api.client_adapter:
        class: AppBundle\Client\Github\ClientAdapter
        arguments:
            - '@github_api.client'


    #####################################


    http_client:
        class: AppBundle\Client\HttpClient
    github_api_client:
        class: AppBundle\Client\GithubApiClient
        arguments:
            - '@http_client'
            - '%env(GITHUB_CLIENT_ID)%'
            - '%env(GITHUB_CLIENT_SECRET)%'
    geolocation_api_client:
        class: AppBundle\Client\GeolocationApiClient
        arguments:
            - '@http_client'
            - '%env(GEOCODING_API_KEY)%'
    api_facade:
        class: AppBundle\Client\ApiFacade
        arguments:
            - '@github_api.client_adapter'
            - '@geolocation_api_client'

    data_provider:
        class: AppBundle\Repository\DataProvider
        autowire: true

    series_provider:
        class: AppBundle\Provider\SeriesProvider
        autowire: true

    factory.contributor:
        class: AppBundle\Factory\ContributorFactory

    builder.contributor:
        class: AppBundle\Builder\ContributorBuilder
        arguments:
            - '@repository.contributor'
            - '@factory.contributor'
            - '@api_facade'

    #################################
    # Helpers
    #################################
    helper.contributor_extractor:
        class: AppBundle\Aggregator\Helper\ContributorExtractor
        lazy: true

    helper.sensiolabs_data_extractor:
        class: AppBundle\Aggregator\Helper\SensiolabsDataExtractor
        lazy: true

    #################################
    # Data aggregators
    #################################
    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPage
        arguments:
            - '@http_client'
            - '@helper.contributor_extractor'
            - '@repository.contributor'

    aggregator.github_user_data:
        class: AppBundle\Aggregator\GithubUserData
        lazy: true
        arguments:
            - '@github_api_client'
            - '@geolocation_api_client'
            - '@repository.contributor'

    aggregator.github_commit_history:
        class: AppBundle\Aggregator\GithubCommitHistory
        lazy: true
        arguments:
            - '@github_api.client_adapter'
            - '@repository.contributor'
            - '@repository.project'
            - '@repository.contribution'
            - '%maintenance_commit_patterns%'

    aggregator.github_commit_history_checker:
        class: AppBundle\Aggregator\GithubCommitHistoryChecker
        lazy: true
        arguments:
            - '@github_api.client_adapter'
            - '@repository.contributor'
            - '@repository.project'
            - '@repository.contribution'
            - '%maintenance_commit_patterns%'

    aggregator.sensiolabs_connect:
        class: AppBundle\Aggregator\SensiolabsConnect
        lazy: true
        arguments:
            - '@http_client'
            - '@helper.sensiolabs_data_extractor'
            - '@repository.contributor'
