services:

    github_api.fake_guzzle_client:
        class: AppBundle\Client\FakeHttpClient

    github_api.http_client:
        class: Http\Adapter\Guzzle6\Client
        arguments:
            - '@github_api.fake_guzzle_client'

    doctrine.orm.purger:
        class: Doctrine\Common\DataFixtures\Purger\ORMPurger
        arguments:
            - '@doctrine.orm.entity_manager'

    behat_doctrine_helper:
        class: features\Helper\DoctrineHelper
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.orm.purger'

    github_api.client_adapter:
        class: features\Fake\ClientAdapterFake

