services:

    github_api.fake_guzzle_client:
        class: AppBundle\Client\FakeHttpClient

    api.http_client:
        class: Http\Adapter\Guzzle6\Client
        arguments:
            - '@github_api.fake_guzzle_client'

    doctrine.orm.purger:
        class: Doctrine\Common\DataFixtures\Purger\ORMPurger
        arguments:
            - '@doctrine.orm.entity_manager'

    behat_doctrine_helper:
        class: features\Helper\DoctrineHelper
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@doctrine.orm.purger'

    # Fake clients
    api.github:
        class: features\Fake\GithubApi

    api.geocoder:
        class: features\Fake\GeocoderApi


    api.list:
        class: features\Helper\ApiCollection
        calls:
            - [ add, ['Github', '@api.github']]
            - [ add, ['Geocoder', '@api.geocoder']]
