services:
    http_client:
        class: GuzzleHttp\Client
    #################################
    # Data aggregators
    #################################

    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPage
        arguments:
            - '@http_client'
            - '@repository.contributor'
    aggregator.git_log:
        class: AppBundle\Aggregator\GitLog
        arguments:
            - '@repository.contributor'
            - '@repository.contribution'
            - '@repository.contribution_history'
            - '%kernel.root_dir%/../git-logs/'

    #################################
    # Data providers
    #################################
    provider.contributors_intersection:
        class: AppBundle\Provider\ContributorsIntersection
        arguments:
            - '@repository.contribution'
            - '@repository.project'
    provider.commit_count_distribution:
        class: AppBundle\Provider\CommitCountDistribution
        arguments:
            - '@repository.contribution'
            - '@repository.project'

    provider.contributors_per_date:
        class: AppBundle\Provider\ContributorsPerDate
        arguments:
            - '@repository.contribution'
