services:

    #################################
    # Data aggregators
    #################################
    aggregator_registry:
        class: AppBundle\Aggregator\AggregatorRegistry

    api.contributor_page:
        class: Aa\ATrends\Api\ContributorPage\ContributorPageApi
        lazy: true
        arguments:
            - '@helper.contributor_extractor'
            - '@page_crawler'

    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPageAggregator
        lazy: true
        arguments:
            - '@api.contributor_page'
            - '@repository.sensiolabs_user'
            - '%sensiolabs_profile_uri%'
        tags:
            - { name: aggregator, alias: 'contributor-pages'}

    aggregator.github_commit:
        class: AppBundle\Aggregator\CommitAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.contributor'
            - '@repository.contribution'
            - '%maintenance_commit_patterns%'
        tags:
            - { name: aggregator, alias: 'commits'}

    aggregator.contributor_country:
        class: AppBundle\Aggregator\ContributorCountryAggregator
        lazy: true
        arguments:
            - '@api.geocoder'
            - '@repository.contributor'
        tags:
            - { name: aggregator, alias: 'contributor-countries'}

    aggregator.sensiolabs_connect:
        class: AppBundle\Aggregator\SensiolabsConnectAggregator
        lazy: true
        arguments:
            - '@page_crawler'
            - '@helper.sensiolabs_data_extractor'
            - '@repository.sensiolabs_user'
        tags:
            - { name: aggregator, alias: 'sensiolabs-profiles'}

    aggregator.github_issue:
        class: AppBundle\Aggregator\IssueAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.issue'
        tags:
            - { name: aggregator, alias: 'issues'}

    aggregator.github_pull_request:
        class: AppBundle\Aggregator\PullRequestAggregator
        lazy: true
        arguments:
            - '@api.github'
            - '@repository.pull_request'
            - '@helper.pull_request_body_processor'
        tags:
            - { name: aggregator, alias: 'pull-requests'}
