services:

    api.http_client:
        class: Http\Adapter\Guzzle6\Client

    api.http_client.buzz:
        class: Http\Adapter\Buzz\Client


    api.cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            - ''
            - 0
            - 'var/api_cache'

    api.geocoder:
        class: Geocoder\Provider\GoogleMaps
        arguments:
            - '@api.http_client.buzz'
            - null
            - null
            - '%env(GEOCODING_API_KEY)%'

    github_api.plugin.wait_and_retry:
        class: AppBundle\Client\Github\WaitAndRetryPlugin
        arguments:
            - '@event_dispatcher'

    github_api.plugin.authentication:
        class: Github\HttpClient\Plugin\Authentication
        arguments:
            - '%env(GITHUB_CLIENT_ID)%'
            - '%env(GITHUB_CLIENT_SECRET)%'
            - 'url_client_id'


    github_api.http_client_builder:
        class: Github\HttpClient\Builder
        arguments:
            - '@api.http_client'
        calls:
            - ['addCache', ['@api.cache']]

    github_api.client_configurator:
        class: AppBundle\Client\Github\ClientConfigurator
        arguments:
            - '@github_api.http_client_builder'
            - ['@github_api.plugin.wait_and_retry', '@github_api.plugin.authentication']

    github_api.client:
        class: Github\Client
        arguments:
            - '@github_api.http_client_builder'
        configurator: ['@github_api.client_configurator', 'configure']

    api.github:
        class: AppBundle\Client\Github\GithubApi
        arguments:
            - '@github_api.client'


    #####################################
    http_client:
        class: AppBundle\Client\HttpClient

    data_provider:
        class: AppBundle\Repository\DataProvider
        autowire: true

    series_provider:
        class: AppBundle\Provider\SeriesProvider
        autowire: true

    #################################
    # Helpers
    #################################
    helper.contributor_extractor:
        class: AppBundle\Aggregator\Helper\ContributorExtractor
        lazy: true

    helper.sensiolabs_data_extractor:
        class: AppBundle\Aggregator\Helper\SensiolabsDataExtractor
        lazy: true

    helper.pull_request_body_processor:
        class: AppBundle\Aggregator\Helper\PullRequestBodyProcessor
        lazy: true
