services:

    #################################
    # Repositories
    #################################
    repository.project:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\Project

    repository.project_version:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\ProjectVersion

    repository.contributor:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\Contributor

    repository.contribution:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\Contribution

    repository.sensiolabs_user:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\SensiolabsUser

    repository.pull_request:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\PullRequest

    repository.pull_request_review:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\PullRequestReview

    repository.pull_request_comment:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\PullRequestComment

    repository.issue:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Aa\ATrends\Entity\Issue
