services:
    http_client:
        class: AppBundle\Client\HttpClient
    github_client:
        class: Github\Client
    github_api_client:
        class: AppBundle\Aggregator\Helper\GithubApiClient
        arguments:
            - '@http_client'
            - '%github.client_id%'
            - '%github.client_secret%'

    #################################
    # Helpers
    #################################
    helper.contributor_extractor:
        class: AppBundle\Aggregator\Helper\ContributorExtractor
        lazy: true

    helper.sensiolabs_data_extractor:
        class: AppBundle\Aggregator\Helper\SensiolabsDataExtractor
        lazy: true

    helper.github_api:
        class: AppBundle\Aggregator\Helper\GithubApiAdapter
        lazy: true
        arguments:
            - '@github_client'
            - '%github.client_id%'
            - '%github.client_secret%'

    #################################
    # Data aggregators
    #################################
    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPage
        arguments:
            - '@http_client'
            - '@helper.contributor_extractor'
            - '@repository.contributor'

    aggregator.git_log:
        class: AppBundle\Aggregator\GitLog
        lazy: true
        arguments:
            - '@repository_facade.contributor'
            - '%kernel.root_dir%/../git-logs/'

    aggregator.github_api:
        class: AppBundle\Aggregator\GithubApi
        lazy: true
        arguments:
            - '@github_api_client'
            - '@repository.contributor'

    aggregator.sensiolabs_connect:
        class: AppBundle\Aggregator\SensiolabsConnect
        lazy: true
        arguments:
            - '@http_client'
            - '@helper.sensiolabs_data_extractor'
            - '@repository.contributor'

    #################################
    # Data providers
    #################################
    provider.contributors_intersection:
        class: AppBundle\Provider\ContributorsIntersection
        lazy: true
        arguments:
            - '@repository.contribution_log'
            - '@repository.project'

    provider.commit_count_distribution:
        class: AppBundle\Provider\CommitCountDistribution
        lazy: true
        arguments:
            - '@repository.contribution_log'
            - '@repository.project'

    provider.contributors_per_date:
        class: AppBundle\Provider\ContributorsPerDate
        lazy: true
        arguments:
            - '@repository.contribution_log'
