services:
    http_client:
        class: GuzzleHttp\Client

    #################################
    # Helpers
    #################################
    helper.contributor_extractor:
        class: AppBundle\Aggregator\Helper\ContributorExtractor
        lazy: true

    #################################
    # Data aggregators
    #################################
    aggregator.contributor_page:
        class: AppBundle\Aggregator\ContributorPage
        lazy: true
        arguments:
            - '@http_client'
            - '@repository.contributor'

    aggregator.git_log:
        class: AppBundle\Aggregator\GitLog
        lazy: true
        arguments:
            - '@repository_facade.contributor'
            - '%kernel.root_dir%/../git-logs/'

    #################################
    # Data providers
    #################################
    provider.contributors_intersection:
        class: AppBundle\Provider\ContributorsIntersection
        lazy: true
        arguments:
            - '@repository.contribution'
            - '@repository.project'

    provider.commit_count_distribution:
        class: AppBundle\Provider\CommitCountDistribution
        lazy: true
        arguments:
            - '@repository.contribution'
            - '@repository.project'

    provider.contributors_per_date:
        class: AppBundle\Provider\ContributorsPerDate
        lazy: true
        arguments:
            - '@repository.contribution'
