services:
    http_client:
        class: GuzzleHttp\Client
    #################################
    # Data crawlers
    #################################
    crawler.contributor_count:
        class: AppBundle\Crawler\ContributorCount
        arguments:
            - '@http_client'
            - '@repository.project_version'
    crawler.contributor_page:
        class: AppBundle\Crawler\ContributorPage
        arguments:
            - '@http_client'
            - '@repository.contributor'
    crawler.git_log:
        class: AppBundle\Crawler\GitLog
        arguments:
            - '@repository.contributor'
            - '@repository.contribution'
            - '%kernel.root_dir%'

    #################################
    # Data providers
    #################################
    provider.contributor_intersection:
        class: AppBundle\Provider\ContributorIntersection
        arguments:
            - '@repository.contribution'
            - '@repository.project'
    provider.commit_count_distribution:
        class: AppBundle\Provider\CommitCountDistribution
        arguments:
            - '@repository.contribution'
            - '@repository.project'
    provider.contributors_per_version:
        class: AppBundle\Provider\ContributorsPerVersion
        arguments:
            - '@repository.project_version'
