services:

    #################################
    # Repositories
    #################################
    repository.contributor:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Contributor
    repository.contribution:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Contribution
    repository.contribution_log:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ContributionLog
    repository.project:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Project
    repository.project_version:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ProjectVersion


    #################################
    # Repository facades
    #################################
    repository_facade.contributor:
        class: AppBundle\Repository\ContributorRepositoryFacade
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@repository.contributor'
            - '@repository.contribution'
            - '@repository.contribution_log'
