parameters:

    trends:

        main:

#           # Not supprted
#           commit_number_growth_per_date:
#                title: 'Commit number growth'
#
#                service: 'provider.contributors_per_date'
#                options:
#                    projects:
#                        - symfony
#                        - symfony-docs
#                chart:
#                    type: line
#

#            contributors_per_country_symfony:
#                title: 'Where Symfony contributors live and work'
#
#                service: 'provider.contributors_per_country'
#                options:
#                    projects:
#                        - symfony
#                chart:
#                    type: map
#
#            contributors_intersection:
#                title: 'How many developers contribute to different projects'
#
#                service: 'provider.contributors_intersection'
#                options:
#                    projects:
#                        - symfony
#                        - symfony-docs
#                chart:
#                    type: venn


            ###################################
            ############# Ready ###############

            commit_count_distribution_symfony:
                title: 'Number of developers who made certain count of commits to Symfony'

                service: 'provider.commit_count_distribution'
                options:
                    project_id: 1
                    chart:
                        type: column

            commit_count_distribution_symfony_docs:
                title: 'Number of developers who made certain count of commits to Symfony docs'

                service: 'provider.commit_count_distribution'
                options:
                    project_id: 2
                    chart:
                        type: column

            contributions_per_date_yearly_symfony:
                title: 'Commit count to Symfony per year'

                service: 'provider.contributions_per_date'
                options:
                    projects:
                        - 1
                    interval: year
                    chart:
                        type: column

            contributions_per_date_yearly_symfony_doc:
                title: 'Commit count to Symfony documentation per year'

                service: 'provider.contributions_per_date'
                options:
                    projects:
                        - 2
                    interval: year
                    chart:
                        type: column



            contributions_per_date_monthly_symfony:
                title: 'Commit count to Symfony per month'

                service: 'provider.contributions_per_date'
                options:
                    projects:
                        - 1
                    interval: month
                    chart:
                        type: area
                        sub-type: stair-step
                        x-axis:
                            type: datetime
