parameters:
    aggregators:

        contributor_page_symfony:
            service: 'aggregator.contributor_page'
            options:
                url: 'http://symfony.com/contributors/code'

        contributor_page_symfony_docs:
            service: 'aggregator.contributor_page'
            options:
                url: 'http://symfony.com/contributors/doc'

        github_user_data:
            service: 'aggregator.github_user_data'
            options: []

        github_commits_symfony:
            service: 'aggregator.github_commit_history'
            options:
                project_id: 1

        github_commit_history_checker:
            service: 'aggregator.github_commit_history_checker'
            options:
                project_id: 1


        github_commits_symfony_docs:
            service: 'aggregator.github_commit_history'
            options:
                project_id: 2

        sensiolabs_connect:
            service: 'aggregator.sensiolabs_connect'
            options: []
