parameters:
    aggregators:

        contributor_page_symfony:
            service: 'aggregator.contributor_page'
            options:
                url: 'http://symfony.com/contributors/code'

        contributor_page_symfony_docs:
            service: 'aggregator.contributor_page'
            options:
                url: 'http://symfony.com/contributors/doc'

        github_api:
            service: 'aggregator.github_api'
            options: []

        github_user_data:
            service: 'aggregator.github_user_data'
            options: []

        github_commit_history:
            service: 'aggregator.github_commit_history'
            options: []

        sensiolabs_connect:
            service: 'aggregator.sensiolabs_connect'
            options: []

        sensiolabs_user_updater:
            service: 'aggregator.sensiolabs_user_updater'
            options: []
