parameters:

    trends:

        # How many developers contribute to different projects
        contributors_intersection:
            title: 'How many developers contribute to different projects'
            type: pie
            series:
                -
                    title: Contributor count
                    data_source: vw_contributor_intersection
                    criteria: {}
                    dimensions: { name: project_names, value: contributor_count, color: color }

        # Where Symfony contributors live and work
        contributors_per_country_symfony:
            title: 'Where Symfony contributors live and work'
            type: map
            series:
                -
                    title: Contributor count
                    data_source: fn_contributor_countries
                    criteria: { year: null }
                    dimensions: { iso: iso, value: contributor_count }

        contributors_per_country_symfony_2016:
            title: 'Where Symfony contributors live and work in 2016'
            type: map
            series:
                -
                    title: Contributor count
                    data_source: fn_contributor_countries
                    criteria: { year: 2016 }
                    dimensions: { iso: iso, value: contributor_count }

        contributions_per_year:
            title: 'Commit count to Symfony code and docs per year'
            type: column
            series:
                -
                    title: Symfony code
                    color: '#4cacdb'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: contribution_count }
                -
                    title: Symfony docs
                    color: '#7aba20'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: contribution_count }

        commit_count_distribution_symfony:
            title: 'Number of developers who made a certain amount of commits to Symfony code'
            type: column
            series:
                -
                    title: Symfony code
                    color: '#4cacdb'
                    data_source: vw_commit_count_distribution
                    criteria:   { project_id: 1 }
                    dimensions: { name: bounds, value: contributor_count }
                -
                    title: Symfony docs
                    color: '#7aba20'
                    data_source: vw_commit_count_distribution
                    criteria:   { project_id: 2 }
                    dimensions: { name: bounds, value: contributor_count }

        contributions_per_year_symfony:
            title: 'Commit count to Symfony code per year'
            type: stairArea
            series:
                -
                    title: All contributors
                    color: '#4cacdb'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: contribution_count }
                -
                    title: Core team
                    color: '#323038'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: core_team_contribution_count }

        contributions_per_year_symfony_docs:
            title: 'Commit count to Symfony docs per year'
            type: stairArea
            series:
                -
                    title: All contributors
                    color: '#7aba20'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: contribution_count }
                -
                    title: Core team
                    color: '#323038'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: core_team_contribution_count }


        contributions_per_month_symfony:
            title: 'Commit count to Symfony code per month'
            type: stairAreaDateTime
            series:
                -
                    title: All contributors
                    color: '#4cacdb'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY-MM-01', year: null }
                    dimensions: { date: date, value: contribution_count }

                -
                    title: Core team
                    color: '#323038'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY-MM-01', year: null }
                    dimensions: { date: date, value: core_team_contribution_count }

        contributions_per_month_symfony_docs:
            title: 'Commit count to Symfony docs per month'
            type: stairAreaDateTime
            series:
                -
                    title: All contributors
                    color: '#7aba20'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY-MM-01', year: null }
                    dimensions: { date: date, value: contribution_count }

                -
                    title: Core team
                    color: '#323038'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY-MM-01', year: null }
                    dimensions: { date: date, value: core_team_contribution_count }

        contributions_per_month_symfony_2016:
            title: 'Commit count to Symfony code per month in 2016'
            type: stairAreaDateTime
            series:
                -
                    title: All contributors
                    color: '#4cacdb'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY-MM-01', year: 2016 }
                    dimensions: { date: date, value: contribution_count }

                -
                    title: Core team
                    color: '#323038'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY-MM-01', year: 2016 }
                    dimensions: { date: date, value: core_team_contribution_count }

        contributions_per_month_symfony_docs_2016:
            title: 'Commit count to Symfony docs per month in 2016'
            type: stairAreaDateTime
            series:
                -
                    title: All contributors
                    color: '#7aba20'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY-MM-01', year: 2016 }
                    dimensions: { date: date, value: contribution_count }

                -
                    title: Core team
                    color: '#323038'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY-MM-01', year: 2016 }
                    dimensions: { date: date, value: core_team_contribution_count }


        maintenance_commits_per_year_symfony:
            title: 'Commit count to Symfony code per year comparing to maintenance commit count'
            type: stairArea
            series:
                -
                    title: All commits
                    color: '#4cacdb'
                    data_source: vw_maintenance_contributions_per_year
                    criteria:   { project_id: 1 }
                    dimensions: { name: date, value: contribution_count }
                -
                    title: Maintenance commits
                    color: '#7c7c7c'
                    data_source: vw_maintenance_contributions_per_year
                    criteria:   { project_id: 1 }
                    dimensions: { name: date, value: maintenance_commit_count }

        maintenance_commits_per_year_symfony_docs:
            title: 'Commit count to Symfony docs per year comparing to maintenance commit count'
            type: stairArea
            series:
                -
                    title: All commits
                    color: '#7aba20'
                    data_source: vw_maintenance_contributions_per_year
                    criteria:   { project_id: 2 }
                    dimensions: { name: date, value: contribution_count }
                -
                    title: Maintenance commits
                    color: '#7c7c7c'
                    data_source: vw_maintenance_contributions_per_year
                    criteria:   { project_id: 2 }
                    dimensions: { name: date, value: maintenance_commit_count }

        contributor_count_per_year_symfony:
            title: 'Contributor count to Symfony code per year'
            type: stairArea
            series:
                -
                    title: All contributors
                    color: '#4cacdb'
                    data_source: fn_contributions
                    criteria:   { project_id: 1, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: contributor_count }
                -
                    title: New contributors
                    color: '#FFF82A'
                    data_source: vw_new_contributors_per_year
                    criteria:   { project_id: 1 }
                    dimensions: { name: date, value: contributor_count }

        contributor_count_per_year_symfony_docs:
            title: 'Contributor count to Symfony docs per year'
            type: stairArea
            series:
                -
                    title: All contributors
                    color: '#7aba20'
                    data_source: fn_contributions
                    criteria:   { project_id: 2, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: contributor_count }
                -
                    title: New contributors
                    color: '#FFF82A'
                    data_source: vw_new_contributors_per_year
                    criteria:   { project_id: 2 }
                    dimensions: { name: date, value: contributor_count }

        # Top-15 contributors to Symfony code by commit counts in 2016
        top_contributors_symfony_2016:
            title: 'Top-15 contributors to Symfony code by commit counts in 2016'
            type: column
            series:
                -
                    title: Commit count
                    color: '#4cacdb'
                    data_source: fn_contributor_contribution_counts
                    criteria:   { project_id: 1, year: 2016 }
                    dimensions: { name: name, value: contribution_count }
                    limit: 15

        top_contributors_symfony_docs_2016:
            title: 'Top-15 contributors to Symfony docs by commit counts in 2016'
            type: column
            series:
                -
                    title: Commit count
                    color: '#7aba20'
                    data_source: fn_contributor_contribution_counts
                    criteria:   { project_id: 2, year: 2016 }
                    dimensions: { name: name, value: contribution_count }
                    limit: 15


        top_new_contributors_symfony_2016:
            title: 'Top-15 new contributors to Symfony code by commit counts in 2016'
            type: column
            series:
                -
                    title: Commit count
                    color: '#4cacdb'
                    data_source: fn_new_contributor_contribution_counts
                    criteria:   { project_id: 1, year: 2016 }
                    dimensions: { name: name, value: contribution_count }
                    limit: 15

        top_new_contributors_symfony_docs_2016:
            title: 'Top-15 new contributors to Symfony docs by commit counts in 2016'
            type: column
            series:
                -
                    title: Commit count
                    color: '#7aba20'
                    data_source: fn_new_contributor_contribution_counts
                    criteria:   { project_id: 2, year: 2016 }
                    limit: 15
                    dimensions: { name: name, value: contribution_count }

        pull_requests_per_date_symfony:
            title: 'Pull requests to Symfony code per year'
            type: stairArea
            series:
                -
                    title: PR count
                    color: '#4cacdb'
                    data_source: fn_pull_requests_per_date
                    criteria:   { project_id: 1, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: pr_count }

        pull_requests_per_date_symfony_docs:
            title: 'Pull requests to Symfony docs per year'
            type: stairArea
            series:
                -
                    title: PR count
                    color: '#7aba20'
                    data_source: fn_pull_requests_per_date
                    criteria:   { project_id: 2, date_format: 'YYYY', year: null }
                    dimensions: { name: date, value: pr_count }


        issues_symfony_per_label_open:
            title: 'Open issues of Symfony code'
            type: pie
            series:
                -
                    title: Open issues
                    data_source: fn_issue_labels
                    criteria:   { project_id: 1, state: 'open', year: null, min_count: 20 }
                    dimensions: { name: label, value: issue_count }

        issues_symfony_per_label_closed:
            title: 'Closed issues of Symfony code'
            type: pie
            series:
                -
                    title: Closed issues
                    data_source: fn_issue_labels
                    criteria:   { project_id: 1, state: 'closed', year: null, min_count: 100 }
                    dimensions: { name: label, value: issue_count }

        issues_symfony_per_label_all:
            title: 'All issues of Symfony code'
            type: pie
            series:
                -
                    title: All issues
                    data_source: fn_issue_labels
                    criteria:   { project_id: 1, state: null, year: null, min_count: 100 }
                    dimensions: { name: label, value: issue_count }

        issues_symfony_per_label_all_2017:
            title: 'All issues of Symfony code in 2017'
            type: pie
            series:
                -
                    title: All issues
                    data_source: fn_issue_labels
                    criteria:   { project_id: 1, state: null, year: 2017, min_count: 3 }
                    dimensions: { name: label, value: issue_count }

        contributors_symfony_with_pr_and_issue_count:
            title: 'Top-25 contributors to Symfony code with their pr and issue counts'
            type: bubble
            x_axis: { title: 'Issue count' }
            y_axis: { title: 'Pull request count' }
            series:
                -
                    title: Contributors
                    data_source: fn_contributor_pull_request_and_issue_count
                    criteria:   { project_id: 1 }
                    limit: 25
                    dimensions: { name: name, x: pr_count, y: issue_count }



    trends-layout:
        index:
            title: 'Main trends'
            charts:
                - { chart: contributors_intersection }
                - { chart: contributors_per_country_symfony }
                - { chart: contributions_per_year }
                - { chart: commit_count_distribution_symfony }
                - { chart: contributions_per_year_symfony }
                - { chart: contributions_per_year_symfony_docs }
                - { chart: contributions_per_month_symfony }
                - { chart: contributions_per_month_symfony_docs }
                - { chart: maintenance_commits_per_year_symfony }
                - { chart: maintenance_commits_per_year_symfony_docs }
                - { chart: contributor_count_per_year_symfony }
                - { chart: contributor_count_per_year_symfony_docs }
                - { chart: pull_requests_per_date_symfony }
                - { chart: pull_requests_per_date_symfony_docs }
                - { chart: issues_symfony_per_label_open }
                - { chart: issues_symfony_per_label_closed }
                - { chart: issues_symfony_per_label_all }
                - { chart: issues_symfony_per_label_all_2017 }
                - { chart: contributors_symfony_with_pr_and_issue_count }

        symfony:
            title: 'Symfony code'
            charts:
                - { chart: contributions_per_year_symfony }
                - { chart: contributions_per_month_symfony }
                - { chart: maintenance_commits_per_year_symfony }
                - { chart: contributor_count_per_year_symfony }

        symfony-docs:
            title: 'Symfony docs'
            charts:
                - { chart: contributions_per_year_symfony_docs }
                - { chart: contributions_per_month_symfony_docs }
                - { chart: maintenance_commits_per_year_symfony_docs }
                - { chart: contributor_count_per_year_symfony_docs }

        symfony-2016:
            title: 'Symfony in 2016'
            charts:
                - { chart: contributors_per_country_symfony_2016 }
                - { chart: contributions_per_month_symfony_2016 }
                - { chart: contributions_per_month_symfony_docs_2016 }
                - { chart: top_contributors_symfony_2016 }
                - { chart: top_contributors_symfony_docs_2016 }
                - { chart: top_new_contributors_symfony_2016 }
                - { chart: top_new_contributors_symfony_docs_2016 }
