parameters:
    aggregators:

        git_log_symfony:
            service: 'aggregator.git_log'
            options:
                project_id: 1
                update_contributions: false
                update_log: true

        git_log_symfony_docs:
            service: 'aggregator.git_log'
            options:
                project_id: 2
                update_contributions: false
                update_log: true

        contributor_page_symfony:
            service: 'aggregator.contributor_page'
            options:
                url: 'http://symfony.com/contributors/code'

        contributor_page_symfony_docs:
            service: 'aggregator.contributor_page'
            options:
                url: 'http://symfony.com/contributors/doc'

        github_api:
            service: 'aggregator.github_api'
            options: []

        github_user_data:
            service: 'aggregator.github_user_data'
            options: []

        sensiolabs_connect:
            service: 'aggregator.sensiolabs_connect'
            options: []
