parameters:

    trends:

        main:

            contributors_intersection:
                title: 'How many developers contribute to different projects'
                chart:
                    type: pie
                series:
                    -
                        title: Contributor count
                        data_source: vw_contributor_intersection
                        criteria: []

                        dimensions:
                            name: project_names
                            value: contributor_count
                            color: color

            contributions_per_date_yearly:
                title: 'Commit count to Symfony code and docs per year'

                chart:
                    type: column

                series:
                    -
                        title: Symfony code
                        color: '#4cacdb'
                        data_source: vw_contributions_per_year
                        criteria:
                            project_id: 1
                        dimensions:
                            name: date
                            value: contribution_count
                    -
                        title: Symfony docs
                        color: '#7aba20'
                        data_source: vw_contributions_per_year
                        criteria:
                            project_id: 2
                        dimensions:
                            name: date
                            value: contribution_count

            commit_count_distribution_symfony:
                title: 'Number of developers who made a certain amount of commits to Symfony code'
                chart:
                    type: column
                series:
                    -
                        title: Symfony code
                        color: '#4cacdb'
                        data_source: vw_commit_count_distribution
                        criteria:
                            project_id: 1
                        dimensions:
                            name: bounds
                            value: contributor_count
                    -
                        title: Symfony docs
                        color: '#7aba20'
                        data_source: vw_commit_count_distribution
                        criteria:
                            project_id: 2
                        dimensions:
                            name: bounds
                            value: contributor_count

            contributions_per_date_yearly_symfony:
                title: 'Commit count to Symfony code per month'

                chart:
                    type: stairArea

                series:
                    -
                        title: All contributors
                        color: '#4cacdb'
                        data_source: vw_contributions_per_year
                        criteria:
                            project_id: 1
                        dimensions:
                            name: date
                            value: contribution_count
                    -
                        title: Core team
                        color: '#323038'
                        data_source: vw_contributions_per_year
                        criteria:
                            project_id: 1
                        dimensions:
                            name: date
                            value: core_team_contribution_count

            contributions_per_date_yearly_symfony_docs:
                title: 'Commit count to Symfony docs per month'

                chart:
                    type: stairArea

                series:
                    -
                        title: All contributors
                        color: '#7aba20'
                        data_source: vw_contributions_per_year
                        criteria:
                            project_id: 2
                        dimensions:
                            name: date
                            value: contribution_count
                    -
                        title: Core team
                        color: '#323038'
                        data_source: vw_contributions_per_year
                        criteria:
                            project_id: 2
                        dimensions:
                            name: date
                            value: core_team_contribution_count

#            contributions_per_date_monthly_symfony:
#                title: 'Commit count to Symfony code per month'
#
#                chart:
#                    type: stairArea
#                    sub-type: stair-step
#                    x-axis:
#                        type: datetime
#
#                criteria:
#                    project_id: 1
#                series:
#                    -
#                        title: Symfony code
#                        color: '#4cacdb'
#                        data_source: vw_contributions_per_year
#                        criteria:
#                            project_id: 1
#                        dimensions:
#                            name: bounds
#                            value: contributor_count

#
#
#            contributions_per_date_yearly_symfony:
#                title: 'Commit count to Symfony code per year'
#
#                service: 'provider.contributions_per_date'
#                options:
#                    projects:
#                        - symfony
#                    interval: year
#                    include_core_team_commits: true
#                    chart:
#                        type: area
#                        sub-type: stair-step
#
#
#            contributions_per_date_monthly_symfony_docs:
#                title: 'Commit count to Symfony docs per month'
#
#                service: 'provider.contributions_per_date'
#                options:
#                    projects:
#                        - symfony-docs
#                    interval: month
#                    include_core_team_commits: true
#                    chart:
#                        type: area
#                        sub-type: stair-step
#                        x-axis:
#                            type: datetime
#
#
#            contributions_per_date_yearly_symfony_docs:
#                title: 'Commit count to Symfony docs per year'
#
#                service: 'provider.contributions_per_date'
#                options:
#                    projects:
#                        - symfony-docs
#                    interval: year
#                    include_core_team_commits: true
#                    chart:
#                        type: area
#                        sub-type: stair-step
#
#            contributors_per_country_symfony:
#                title: 'Where Symfony contributors live and work'
#
#                service: 'provider.contributors_per_country'
#                options:
#                    projects:
#                        - symfony
#                    chart:
#                        type: map
