parameters:
    aggregators:

        github_commits:
            service: 'aggregator.github_commit'
            projects: ['symfony', 'symfony-docs']
            options: []

        contributor_country:
            service: 'aggregator.contributor_country'
            projects: ['symfony']
            options: []

        github_issues:
            service: 'aggregator.issue'
            projects: ['symfony', 'symfony-docs']
            options: []

        github_pr:
            service: 'aggregator.pull_request'
            projects: ['symfony', 'symfony-docs']
            options: []


        # Checkers
        github_commits_symfony_checker:
            service: 'aggregator.github_commit_checker'
            options:
                project_id: 1
