parameters:
    aggregators:

        github_commits:
            service: 'aggregator.github_commit'
            projects: ['symfony', 'symfony-docs']
            options: []

        contributor_country:
            service: 'aggregator.contributor_country'
            projects: ['symfony']
            options: []

        github_issues:
            service: 'aggregator.github_issue'
            projects: ['symfony', 'symfony-docs']
            options: []

        github_pull_requests:
            service: 'aggregator.github_pull_request'
            projects: ['symfony', 'symfony-docs']
            options: []

